cmake_minimum_required(VERSION 3.21)
include("${SOURCE_ROOT}/cmake/SourceFingerprint.cmake")
# All mutations are confined to a generated fixture in the test build directory.
set(root "${WORK_ROOT}/fixture")
file(REMOVE_RECURSE "${WORK_ROOT}")
file(MAKE_DIRECTORY "${root}/src" "${root}/cmake" "${root}/assets")
file(COPY "${SOURCE_ROOT}/cmake/SourceFingerprint.cmake" DESTINATION "${root}/cmake")
file(WRITE "${root}/CMakeLists.txt" [=[
cmake_minimum_required(VERSION 3.21)
project(FingerprintFixture NONE)
include(cmake/SourceFingerprint.cmake)
pettime_source_fingerprint("${CMAKE_CURRENT_SOURCE_DIR}" value)
file(GENERATE OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/fingerprint.txt" CONTENT "${value}")
add_custom_target(fingerprint ALL)
]=])
file(WRITE "${root}/resources.qrc" "<RCC/>\n")
file(WRITE "${root}/src/example.cpp" "// one\n// two\n")
file(WRITE "${root}/assets/test.bin" "binary-data")
pettime_source_fingerprint("${root}" baseline)
file(COPY "${root}/" DESTINATION "${WORK_ROOT}/other-path")
pettime_source_fingerprint("${WORK_ROOT}/other-path" moved)
if(NOT baseline STREQUAL moved)
    message(FATAL_ERROR "Absolute checkout path changed fingerprint")
endif()
file(WRITE "${root}/src/example.cpp" "// one\r\n// two\r\n")
pettime_source_fingerprint("${root}" crlf)
if(NOT baseline STREQUAL crlf)
    message(FATAL_ERROR "CRLF changed fingerprint")
endif()
file(WRITE "${root}/README.md" "unrelated documentation")
file(MAKE_DIRECTORY "${root}/tests")
file(WRITE "${root}/tests/example.cpp" "unrelated test")
pettime_source_fingerprint("${root}" docs)
if(NOT baseline STREQUAL docs)
    message(FATAL_ERROR "Documentation/tests changed fingerprint")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${root}" -B "${WORK_ROOT}/build"
    -G "${TEST_GENERATOR}" RESULT_VARIABLE result OUTPUT_QUIET ERROR_VARIABLE error)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Fixture configuration failed: ${error}")
endif()
function(check_build expected)
    execute_process(COMMAND "${CMAKE_COMMAND}" --build "${WORK_ROOT}/build"
        RESULT_VARIABLE result OUTPUT_QUIET ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Fixture build failed: ${error}")
    endif()
    file(READ "${WORK_ROOT}/build/fingerprint.txt" actual)
    if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "Incremental build did not update the fingerprint")
    endif()
endfunction()
check_build("${baseline}")
foreach(kind IN ITEMS modify add remove asset)
    if(kind STREQUAL "modify")
        file(APPEND "${root}/src/example.cpp" "// changed\n")
    elseif(kind STREQUAL "add")
        file(WRITE "${root}/src/new.h" "// new header\n")
    elseif(kind STREQUAL "remove")
        file(REMOVE "${root}/src/new.h")
    else()
        file(APPEND "${root}/assets/test.bin" "changed")
    endif()
    pettime_source_fingerprint("${root}" changed)
    if(changed STREQUAL baseline)
        message(FATAL_ERROR "${kind} did not change fingerprint")
    endif()
    check_build("${changed}")
    set(baseline "${changed}")
endforeach()
message(STATUS "Fingerprint reproducibility and automatic rebuild checks passed")
