# Stable across checkout paths, operating systems and text line endings.
function(pettime_source_fingerprint root output)
    if(NOT CMAKE_SCRIPT_MODE_FILE)
        set(watch CONFIGURE_DEPENDS)
    endif()
    file(GLOB_RECURSE inputs ${watch} RELATIVE "${root}"
        "${root}/src/*.cpp" "${root}/src/*.h" "${root}/assets/*"
        "${root}/cmake/*.cmake")
    list(APPEND inputs CMakeLists.txt resources.qrc)
    list(SORT inputs)
    set(manifest "pettime-source-v1\n")
    foreach(path IN LISTS inputs)
        if(path MATCHES "\\.(cpp|h|cmake|txt|qrc)$")
            file(READ "${root}/${path}" content)
            string(REPLACE "\r\n" "\n" content "${content}")
            string(SHA256 digest "${content}")
        else()
            file(SHA256 "${root}/${path}" digest)
        endif()
        string(APPEND manifest "${path}:${digest}\n")
        if(NOT CMAKE_SCRIPT_MODE_FILE)
            set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${root}/${path}")
        endif()
    endforeach()
    string(SHA256 fingerprint "${manifest}")
    set(${output} "${fingerprint}" PARENT_SCOPE)
endfunction()
